language: python

python:
  - "2.7"

sudo: true
cache: pip

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow
      - bzr
      - wkhtmltopdf

env:
  - VERSION="7.0" LINT_CHECK="1"
  - VERSION="7.0" ODOO_REPO="odoo/odoo" LINT_CHECK="0"
  - VERSION="7.0" ODOO_REPO="OCA/OCB" LINT_CHECK="0"
  - VERSION="7.0" UNIT_TEST="1" LINT_CHECK="0"


before_install:
  - sudo pip install GitPython bzr
  - sudo pip install cairosvg==1.0.22
  - sudo pip install unicodecsv
  - sudo pip install pyBarcode==0.7


virtualenv:
  system_site_packages: true

install:
  - git clone https://github.com/oca/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
